spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

server:
  max-http-request-header-size: 16KB
  port: 8222
