eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

keycloak:
  realm: iamrutra
  auth-server-url: http://localhost:8080/realm/iamrutra
  resource: springboot-keycloak
  public-client: true
  bearer-only: false

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/iamrutra/protocol/openid-connect/certs
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: user-service
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/users/**
        - id: post-service
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/posts/**
        - id: like-service
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/likes/**
        - id: comment-service
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/comments/**
      discovery:
        locator:
          enabled: true
