server:
  port: 8030
spring:


  mail:
    host: mail-dev
    port: 1025
    username: root
    password: root
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
