server:
  port: 8030
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: '*'
      spring.json.type.mapping: commentEvent:com.iamrutra.notification_service.events.CommentEvent,likeEvent:com.iamrutra.notification_service.events.LikeEvent


  mail:
    host: mail-dev
    port: 1025
    username: root
    password: root
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
