spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
            google:
                client-id: 736076515726-sbjvsptle424r1of631rjofkhgfvu42e.apps.googleusercontent.com
                client-secret: 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
    user:
      name: admin
      password: admin


